using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Virus3 : MonoBehaviour
{
    public GameObject  virus3;
    private States _states;
    
    // Update is called once per frame
    void Update()
    {
        if (BattleMachine2.IsEnemyChoosing)
        {
            RandomState.StateLimits = 4 ;
            RandomState.RandomStateMethod();
            Debug.Log("Enemy is Choosing");

            switch (RandomState.StateE)
            {
                case 1:
                    _states.Attack();
                    Debug.Log("2-Attack");
                    break;
                case 2:
                    _states.Pixeling();
                    Debug.Log("2-Pixel");
                    break;
                case 3:
                    _states.Light();
                    Debug.Log("2-Light");
                    break;
                case 4:
                    _states.Bug();
                    Debug.Log("2-Bug");
                    break;
                default:
                    _states.Iddle();
                    Debug.Log("3-idle");
                    break;
            }
            BattleMachine2.IsEnemyChoosing = false;
            BattleMachine2.OnPlayerTurn = true;
        }
    }
}
