using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Enemy3 : MonoBehaviour
{
    public GameObject  virus3, virus2;
    public static bool IsVirus3Playing=false;
    public static bool IsVirus2Playing=false;

    private int c = 0;

    // Update is called once per frame
    void Update()
    {
        if (BattleMachine3.IsEnemyChoosing)
        {
            if (c % 2 == 0)
            {
                Debug.Log("Enemy 3 Selected");
                Virus3Again virus1Controller = virus3.GetComponent<Virus3Again>();
                IsVirus3Playing = true;
                BattleMachine3.IsEnemyChoosing = false;

            }
            else
            {
                Debug.Log("Enemy 2 Selected");
                Virus2 virus2Controller = virus2.GetComponent<Virus2>();
                IsVirus2Playing = true;
                BattleMachine3.IsEnemyChoosing = false;
            }
        }
        c++;
    }
}
