using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Virus3Again : MonoBehaviour
{
    public GameObject  virus3;
    private States _states;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (BattleMachine2.IsEnemyChoosing)
        {
            RandomState.StateLimits = 4 ;
            RandomState.RandomStateMethod();
            Debug.Log("Virus 3 is Choosing");

            switch (RandomState.StateE)
            {
                case 1:
                    _states.Attack();
                    Debug.Log("2-Attack");
                    Enemy3.IsVirus3Playing = false;
                    BattleMachine3.IsEnemyChoosing = false;
                    BattleMachine3.OnPlayerTurn = true;
                    break;
                case 2:
                    _states.Pixeling();
                    Debug.Log("2-Pixel");
                    Enemy3.IsVirus3Playing = false;
                    BattleMachine3.IsEnemyChoosing = false;
                    BattleMachine3.OnPlayerTurn = true;
                    break;
                case 3:
                    _states.Light();
                    Debug.Log("2-Light");
                    Enemy3.IsVirus3Playing = false;
                    BattleMachine3.IsEnemyChoosing = false;
                    BattleMachine3.OnPlayerTurn = true;
                    break;
                case 4:
                    _states.Bug();
                    Debug.Log("2-Bug");
                    Enemy3.IsVirus3Playing = false;
                    BattleMachine3.IsEnemyChoosing = false;
                    BattleMachine3.OnPlayerTurn = true;
                    break;
                default:
                    _states.Iddle();
                    Debug.Log("3-idle");
                    break;
            }
        }
    }
}
