using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Virus2 : MonoBehaviour
{
    private Vector3 _initialPosition;
    
    private States _states;
    
    [SerializeField] private MovementVirus2 _movementVirus2;
    // Start is called before the first frame update
    void Update()
    {
        if (Enemy.IsVirus1Playing)
        {
            RandomState.StateLimits =3 ;
            RandomState.RandomStateMethod();
            switch (RandomState.StateE)
            {
                case 1: 
                    _states.Shoot();
                    Debug.Log("2-Shoot");
                    Enemy3.IsVirus2Playing = false;
                    BattleMachine3.IsEnemyChoosing = false;
                    BattleMachine3.OnPlayerTurn = true;
                    break;
                case 2: 
                    _states.Block();
                    Debug.Log("2-Blocking");
                    Enemy3.IsVirus2Playing = false;
                    BattleMachine3.IsEnemyChoosing = false;
                    BattleMachine3.OnPlayerTurn = true;
                    break;
                case 3: 
                    _states.Steal();
                    Debug.Log("2-Steal");
                    Enemy3.IsVirus2Playing = false;
                    BattleMachine3.IsEnemyChoosing = false;
                    BattleMachine3.OnPlayerTurn = true;
                    break;
                default:
                    _states.Iddle();
                    Debug.Log("2-Iddle");
                    Enemy3.IsVirus2Playing = false;
                    BattleMachine3.IsEnemyChoosing = false;
                    BattleMachine3.OnPlayerTurn = true;
                    break;
            }
        }
    }
}
